### Create a hotel
POST http://localhost:5000/api/v1/hotels
Content-Type: application/json

{
    "name": "Grand Hotel",
    "type": "Hotel",
    "city": "Pune",
    "address": "somewhere",
    "distance": "500",
    "title": "Best hotel in the city",
    "desc": "hotel description",
    "cheapestPrice": 200
}

### Get all hotels
GET http://localhost:5000/api/v1/hotels?min=100&max=250&limit=5&featured=false


### Get single hotel
GET http://localhost:5000/api/v1/hotels/3

### Get hotel rooms
GET http://localhost:5000/api/v1/hotels/1/rooms

### Update a hotel
PATCH http://localhost:5000/api/v1/hotels/3
Content-Type: application/json

{
    "name": "Updated hotel name"
}

### Delete a hotel
DELETE http://localhost:5000/api/v1/hotels/3

### Get hotel count by city
GET http://localhost:5000/api/v1/hotels/countByCity?cities=Pune,madrid,akurdi,pune

### Get count by type
GET http://localhost:5000/api/v1/hotels/countByType