### Get all users
GET http://localhost:5000/api/v1/users

### Get single user
GET http://localhost:5000/api/v1/users/2

### Get current user
GET http://localhost:5000/api/v1/users/currentUser


### Update user
PATCH http://localhost:5000/api/v1/users/1
Content-Type: application/json

{
    "isAdmin": true
}

### Delete user
DELETE http://localhost:5000/api/v1/users/1
