### Create a new user
POST http://localhost:5000/api/v1/auth/register
Content-Type: application/json

{
    "username": "john", 
    "email": "john@gmail.com",
    "country": "Russia",
    "city": "Moscow",
    "phone": "5465455454",
    "password": "secret",
    "isAdmin": false
}

### Login user
POST http://localhost:5000/api/v1/auth/login
Content-Type: application/json

{
    "username": "john",
    "password": "secret"
}

### Logout user
GET http://localhost:5000/api/v1/auth/logout
